name: progress_builder
description: A simple wrapper for asynchronous actions with progress/loading indicators and error handling.
version: 1.1.4
homepage: https://github.com/apexlabs-ai/progress_builder

environment:
  sdk: ">=2.13.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  mounted_state: ^1.0.1

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
